-- Benefit Lab admin security hardening and management schema.
-- All management data is server-only and accessed with the service role.

create extension if not exists pgcrypto with schema extensions;

alter table public.admin_users enable row level security;
alter table public.admin_invite_keys enable row level security;

create unique index if not exists admin_users_unique_code_key
  on public.admin_users (unique_code);

create index if not exists admin_invite_keys_created_by_idx
  on public.admin_invite_keys (created_by);

create table if not exists public.partners (
  id uuid primary key default gen_random_uuid(),
  login_id text not null unique,
  password_hash text,
  nickname text not null,
  unique_code text not null unique,
  phone text,
  level integer not null default 1 check (level >= 1),
  bank_name text,
  account_number text,
  account_holder text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inquiries (
  id uuid primary key default gen_random_uuid(),
  name text,
  referrer_url text,
  phone_number text not null,
  install_location text,
  install_count integer not null default 0 check (install_count >= 0),
  marketer_code text not null default '',
  status text not null default 'new'
    check (status in ('new', 'in_progress', 'contracted', 'cancelled')),
  inquiry_type text not null default 'consultation'
    check (inquiry_type in ('consultation', 'installation')),
  landing_template text,
  landing_subtype text,
  reservation_date date,
  reservation_time_slot text
    check (reservation_time_slot is null or reservation_time_slot in ('morning', 'afternoon')),
  outdoor_count integer not null default 0 check (outdoor_count >= 0),
  indoor_count integer not null default 0 check (indoor_count >= 0),
  address text,
  address_detail text,
  zonecode text,
  documents jsonb not null default '{}'::jsonb
    check (jsonb_typeof(documents) = 'object'),
  documents_submitted boolean not null default false,
  privacy_consent boolean not null default true,
  submitted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.guide_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.guides (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  content text not null,
  is_published boolean not null default false,
  category_id uuid references public.guide_categories(id) on delete set null,
  created_by uuid references public.admin_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.settlements (
  id bigint generated by default as identity primary key,
  partner_code text not null,
  partner_nickname text not null,
  settlement_date date not null,
  file_name text not null,
  file_path text not null unique,
  content_type text not null,
  file_size bigint not null check (file_size > 0),
  created_by uuid references public.admin_users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists partners_created_at_idx
  on public.partners (created_at desc);
create index if not exists inquiries_status_submitted_at_idx
  on public.inquiries (status, submitted_at desc);
create index if not exists inquiries_marketer_code_idx
  on public.inquiries (marketer_code);
create index if not exists guide_categories_display_order_idx
  on public.guide_categories (display_order, name);
create index if not exists guides_category_id_idx
  on public.guides (category_id);
create index if not exists guides_updated_at_idx
  on public.guides (updated_at desc);
create index if not exists settlements_partner_date_idx
  on public.settlements (partner_code, settlement_date desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists partners_set_updated_at on public.partners;
create trigger partners_set_updated_at
  before update on public.partners
  for each row execute function public.set_updated_at();

drop trigger if exists inquiries_set_updated_at on public.inquiries;
create trigger inquiries_set_updated_at
  before update on public.inquiries
  for each row execute function public.set_updated_at();

drop trigger if exists guide_categories_set_updated_at on public.guide_categories;
create trigger guide_categories_set_updated_at
  before update on public.guide_categories
  for each row execute function public.set_updated_at();

drop trigger if exists guides_set_updated_at on public.guides;
create trigger guides_set_updated_at
  before update on public.guides
  for each row execute function public.set_updated_at();

create or replace function public.register_admin_with_invite(
  p_invite_key text,
  p_login_id text,
  p_password_hash text,
  p_nickname text
)
returns table (
  user_id uuid,
  user_login_id text,
  user_nickname text,
  user_unique_code text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user public.admin_users%rowtype;
begin
  update public.admin_invite_keys
  set is_used = true
  where key = p_invite_key
    and is_used = false
    and expires_at > now();

  if not found then
    raise exception using
      errcode = 'P0001',
      message = 'invalid_or_expired_invite_key';
  end if;

  insert into public.admin_users (
    login_id,
    password_hash,
    unique_code,
    nickname
  )
  values (
    p_login_id,
    p_password_hash,
    'S-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8)),
    p_nickname
  )
  returning * into v_user;

  return query
  select v_user.id, v_user.login_id, v_user.nickname, v_user.unique_code;
end;
$$;

alter table public.partners enable row level security;
alter table public.inquiries enable row level security;
alter table public.guide_categories enable row level security;
alter table public.guides enable row level security;
alter table public.settlements enable row level security;

revoke all privileges on table public.admin_users from anon, authenticated;
revoke all privileges on table public.admin_invite_keys from anon, authenticated;
revoke all privileges on table public.partners from anon, authenticated;
revoke all privileges on table public.inquiries from anon, authenticated;
revoke all privileges on table public.guide_categories from anon, authenticated;
revoke all privileges on table public.guides from anon, authenticated;
revoke all privileges on table public.settlements from anon, authenticated;

revoke insert, update, delete, truncate, references, trigger
  on table public.cards from anon, authenticated;
grant select on table public.cards to anon, authenticated;

grant all privileges on table public.admin_users to service_role;
grant all privileges on table public.admin_invite_keys to service_role;
grant all privileges on table public.partners to service_role;
grant all privileges on table public.inquiries to service_role;
grant all privileges on table public.guide_categories to service_role;
grant all privileges on table public.guides to service_role;
grant all privileges on table public.settlements to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke all on function public.register_admin_with_invite(text, text, text, text)
  from public, anon, authenticated;
grant execute on function public.register_admin_with_invite(text, text, text, text)
  to service_role;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'benefit-lab-private',
  'benefit-lab-private',
  false,
  10485760,
  array['application/pdf', 'image/jpeg', 'image/png']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
